name: "Build & Push"

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: interop-debezium-postgresql:build
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 1

  push:
    name: Push (dev)
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Push to ECR
        uses: ./.github/actions/push
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE_ARN }}
          repository: interop-debezium-postgresql

  knodia_terraform:
    name: Terraform Apply (knodia-dev)
    runs-on: ubuntu-latest
    environment: knodia-dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.IAM_ROLE_ARN }}
          role-session-name: interop-debezium-postgresql-tf-${{ github.run_number }}

      - name: Read terraform version
        working-directory: terraform/
        run: |
          echo "TERRAFORM_VERSION=$(cat ./.terraform-version)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Apply
        working-directory: terraform/
        env:
          ENV: dev
        run: |
          terraform fmt -check -recursive
          ./terraform.sh apply "$ENV" -auto-approve

  knodia_push:
    name: Push (knodia-dev)
    needs: [build, knodia_terraform]
    runs-on: ubuntu-latest
    environment: knodia-dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Push to ECR
        uses: ./.github/actions/push
        with:
          aws_region: ${{ vars.AWS_REGION }}
          iam_role_arn: ${{ vars.IAM_ROLE_ARN }}
          repository: knodia-infra-debezium-postgresql
